<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "scientist".
 *
 * @property integer $id
 * @property string $name
 * @property string $city
 * @property string $biography
 * @property string $achievements
 */
class Scientist extends \yii\db\ActiveRecord
{
    /**
     * Статус ученого: активен.
     */
    const STATUS_ACTIVE = 1;
    /**
     * Статус ученого: удален.
     */
    const STATUS_DELETE = 0;

    public $file;
    public $del_img;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'scientist';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'city', 'biography', 'achievements'], 'required'],
            [['biography', 'achievements'], 'string'],
            [['name', 'city'], 'string', 'max' => 255],
            [['file'], 'file', 'extensions' => 'png, jpg'],
            [['del_img'], 'boolean'],

        ];
    }

    /**
     *
     */
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        
        if (!file_exists(Yii::getAlias('@frontend/web'.$this->image)) OR $this->image == '') {
            $this->image = '/images/teacher.jpg';
        }
        //$this->image?:'/images/teacher.jpg';

        Yii::info('its event after find file exist '.$this->image, __METHOD__);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'city' => 'City',
            'biography' => 'Biography',
            'achievements' => 'Achievements',
            'status' => 'Статус',
        ];
    }

    //public function getScientist($id)
    //{
    //    if (
    //        ($model = Post::findOne($id)) !== null &&
    //        $model->isPublished()
    //    ) {
    //        return $model;
    //    } else {
    //        throw new NotFoundHttpException('The requested post does not exist.');
    //    }
    //}
//
    //protected function isPublished()
    //{
    //    return $this->publish_status === self::STATUS_PUBLISH;
    //}
}
